# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JTH Develops
email: contact@jthdevelops.com
description: > # this means to ignore newlines until "baseurl:"
  JTH Develops custom solutions to technical difficulties.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jthdevelops.com" # the base hostname & protocol for your site
twitter_username: JTHDevelops
github_username:  JTHDevelops

# Build settings
markdown: kramdown
